"""
Train the pairwise matching classifier.

Frames matching as binary classification over (S1, candidate) pairs
generated by the blocking stage: label=1 if the pair is in ground truth,
label=0 otherwise (i.e. a candidate that blocking surfaced but that is
not a true match — these are exactly the "look-alikes" the model must
learn to reject to keep precision high under F_0.5).
"""

import lightgbm as lgb
import numpy as np
from sklearn.model_selection import GroupKFold

from features import FEATURE_NAMES, build_feature_matrix


def build_training_table(candidates: dict, gt_exploded, s1_lookup: dict, other_lookup: dict):
    """
    candidates: {source1_entity_id: set(candidate_ids)} from blocking, computed
                on the TRAIN split.
    gt_exploded: long DataFrame [source1_entity_id, matched_entity_id] of
                 true positive pairs (from io_utils.explode_ground_truth).
    Returns: X (features), y (labels), groups (source1_entity_id, for
             group-aware CV so a whole S1 entity's pairs stay together).
    """
    import pandas as pd

    true_pairs = set(zip(gt_exploded["source1_entity_id"], gt_exploded["matched_entity_id"]))

    rows = []
    for s1, cands in candidates.items():
        for cand in cands:
            label = 1 if (s1, cand) in true_pairs else 0
            rows.append((s1, cand, label))
    pairs_df = pd.DataFrame(rows, columns=["source1_entity_id", "candidate_entity_id", "label"])

    X = build_feature_matrix(pairs_df, s1_lookup, other_lookup)
    y = pairs_df["label"].values
    groups = pairs_df["source1_entity_id"].values
    return X, y, groups, pairs_df


def train_lightgbm(X, y, groups, n_splits: int = 5, params: dict = None):
    """
    Group-aware CV training (so no S1 entity leaks between fold train/val)
    and returns a list of fold models plus out-of-fold predicted
    probabilities for threshold tuning.
    """
    default_params = dict(
        objective="binary",
        metric="average_precision",
        num_leaves=31,
        learning_rate=0.05,
        n_estimators=400,
        min_child_samples=10,
        subsample=0.8,
        colsample_bytree=0.8,
        # Positives (true matches) are rare relative to look-alike
        # candidates; weight them up so the model doesn't just predict
        # "no match" everywhere.
        is_unbalance=True,
        random_state=42,
    )
    if params:
        default_params.update(params)

    gkf = GroupKFold(n_splits=n_splits)
    oof_pred = np.zeros(len(y))
    models = []

    for fold, (train_idx, val_idx) in enumerate(gkf.split(X, y, groups)):
        model = lgb.LGBMClassifier(**default_params)
        model.fit(
            X[train_idx], y[train_idx],
            eval_set=[(X[val_idx], y[val_idx])],
            callbacks=[lgb.early_stopping(30, verbose=False)],
        )
        oof_pred[val_idx] = model.predict_proba(X[val_idx])[:, 1]
        models.append(model)
        print(f"Fold {fold}: trained on {len(train_idx)} pairs, validated on {len(val_idx)} pairs")

    return models, oof_pred


def predict_with_ensemble(models, X):
    """Average predicted probability across fold models."""
    preds = np.zeros(len(X))
    for m in models:
        preds += m.predict_proba(X)[:, 1]
    return preds / len(models)


def feature_importance_report(models):
    import pandas as pd
    imp = np.mean([m.feature_importances_ for m in models], axis=0)
    return pd.DataFrame({"feature": FEATURE_NAMES, "importance": imp}).sort_values(
        "importance", ascending=False
    )
